services:
  server:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
  
  celery:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    command: celery -A mysite worker --loglevel=INFO --concurrency=4
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: celery -A mysite flower --port=5555
    depends_on:
      - redis
      - celery
