services:
  server:
    build:
      context: .
    image: 194139654926.dkr.ecr.us-east-2.amazonaws.com/autoblog-ec2:server
    env_file:
      - .env
      - .env.prod
    expose:
      - 8000
    volumes:
      - ./:/app
      - static_volume:/app/web/staticfiles
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
  
  celery:
    build:
      context: .
    volumes:
      - ./:/app
    env_file:
      - .env
    command: celery -A mysite worker --loglevel=INFO --concurrency=4
    depends_on:
      - redis

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    image: 194139654926.dkr.ecr.us-east-2.amazonaws.com/autoblog-ec2:nginx-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/app/web/staticfiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - server

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - .env.prod.proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  certs:
  html:
  vhost:
  acme:
