services:
  server:
    build:
      context: .
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - ./:/app
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
  
  celery:
    build:
      context: .
    volumes:
      - ./:/app
    env_file:
      - .env
    command: celery -A mysite worker --loglevel=INFO --concurrency=4
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: celery -A mysite flower --port=5555
    depends_on:
      - redis
      - celery

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - server

volumes:
  static_volume:
