services:
  server:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - static_volume:/app/web/staticfiles
      - media_volume:/app/web/mediafiles

    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
  
  celery:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    volumes:
      - ./:/app
      - media_volume:/app/web/mediafiles
    env_file:
      - .env
    command: celery -A mysite worker --loglevel=INFO --concurrency=4
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: celery -A mysite flower --port=5555
    depends_on:
      - redis
      - celery

  nginx:
    build: ./nginx-local
    volumes:
      - static_volume:/app/web/staticfiles
      - media_volume:/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - server

volumes:
  static_volume:
  media_volume: